# Generated by Django 4.0.1 on 2022-01-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=60)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
    ]
