# Generated by Django 4.0.1 on 2022-01-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_entry_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('housing', 'Housing'), ('transportation', 'Transportation'), ('fun & entertainment', 'Fun & Entertainment'), ('investing', 'Investing'), ('interest & debts', 'Interest & Debts'), ('allowance', 'Allowance'), ('work', 'Work'), ('investment returns', 'Investment Returns')], default='food', max_length=60),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='income', max_length=50),
        ),
    ]
