# Generated by Django 4.0.1 on 2022-02-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_alter_entry_category_alter_entry_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], default='income', max_length=50),
        ),
    ]
