# Generated by Django 4.0.1 on 2022-02-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_alter_entry_amount_alter_entry_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
