# Generated by Django 4.0.1 on 2022-02-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_alter_entry_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='username',
            field=models.CharField(default='User', max_length=50),
        ),
    ]
